CREATE TABLE nobel (yr int(11) NULL, subject varchar(15) NULL, winner varchar(50) NULL);
INSERT INTO nobel VALUES ("2015","Chemistry","Aziz Sancar");
INSERT INTO nobel VALUES ("2015","Chemistry","Paul L. Modrich");
INSERT INTO nobel VALUES ("2015","Chemistry","Tomas Lindahl");
INSERT INTO nobel VALUES ("2015","Economics","Angus Deaton");
INSERT INTO nobel VALUES ("2015","Literature","Svetlana Alexievich");
INSERT INTO nobel VALUES ("2015","Medicine","Tu Youyou");
INSERT INTO nobel VALUES ("2015","Medicine","William C. Campbell");
INSERT INTO nobel VALUES ("2015","Peace","Tunisian National Dialogue Quartet");
INSERT INTO nobel VALUES ("2015","Physics","Arthur B. McDonald");
INSERT INTO nobel VALUES ("2015","Physics","Takaaki Kajita");
INSERT INTO nobel VALUES ("2014","Chemistry","Eric Betzig");
INSERT INTO nobel VALUES ("2014","Chemistry","Stefan Hell");
INSERT INTO nobel VALUES ("2014","Chemistry","William Moerner");
INSERT INTO nobel VALUES ("2014","Economics","Jean Tirole");
INSERT INTO nobel VALUES ("2014","Literature","Patrick Modiano");
INSERT INTO nobel VALUES ("2014","Medicine","Edvard Moser");
INSERT INTO nobel VALUES ("2014","Medicine","John O'Keefe");
INSERT INTO nobel VALUES ("2014","Medicine","May-Britt Moser");
INSERT INTO nobel VALUES ("2014","Peace","Kailash Satyarthi");
INSERT INTO nobel VALUES ("2014","Peace","Malala Yousafzai");
INSERT INTO nobel VALUES ("2014","Physics","Hiroshi Amano");
INSERT INTO nobel VALUES ("2014","Physics","Isamu Akasaki");
INSERT INTO nobel VALUES ("2014","Physics","Shuji Nakamura");
INSERT INTO nobel VALUES ("2013","Chemistry","Arieh Warshel");
INSERT INTO nobel VALUES ("2013","Chemistry","Martin Karplus");
INSERT INTO nobel VALUES ("2013","Chemistry","Michael Levitt");
INSERT INTO nobel VALUES ("2013","Economics","Eugene F. Fama");
INSERT INTO nobel VALUES ("2013","Economics","Lars Peter Hansen");
INSERT INTO nobel VALUES ("2013","Economics","Robert J. Shiller");
INSERT INTO nobel VALUES ("2013","Literature","Alice Munro");
INSERT INTO nobel VALUES ("2013","Medicine","James E. Rothman");
INSERT INTO nobel VALUES ("2013","Medicine","Randy W. Schekman");
INSERT INTO nobel VALUES ("2013","Medicine","Thomas C. Südhof");
INSERT INTO nobel VALUES ("2013","Physics","François Englert");
INSERT INTO nobel VALUES ("2013","Physics","Peter W. Higgs");
INSERT INTO nobel VALUES ("2012","Chemistry","Brian K. Kobilka");
INSERT INTO nobel VALUES ("2012","Chemistry","Robert J. Lefkowitz");
INSERT INTO nobel VALUES ("2012","Economics","Alvin E. Roth");
INSERT INTO nobel VALUES ("2012","Economics","Lloyd S. Shapley");
INSERT INTO nobel VALUES ("2012","Literature","Mo Yan");
INSERT INTO nobel VALUES ("2012","Medicine","John B. Gurdon");
INSERT INTO nobel VALUES ("2012","Medicine","Shinya Yamanaka");
INSERT INTO nobel VALUES ("2012","Peace","European Union");
INSERT INTO nobel VALUES ("2012","Physics","David J. Wineland");
INSERT INTO nobel VALUES ("2012","Physics","Serge Haroche");
INSERT INTO nobel VALUES ("2011","Chemistry","Dan Shechtman");
INSERT INTO nobel VALUES ("2011","Economics","Christopher A. Sims");
INSERT INTO nobel VALUES ("2011","Economics","Thomas J. Sargent");
INSERT INTO nobel VALUES ("2011","Literature","Tomas Tranströmer");
INSERT INTO nobel VALUES ("2011","Medicine","Bruce Beutler");
INSERT INTO nobel VALUES ("2011","Medicine","Jules A. Hoffmann");
INSERT INTO nobel VALUES ("2011","Medicine","Ralph M. Steinman");
INSERT INTO nobel VALUES ("2011","Peace","Ellen Johnson Sirleaf");
INSERT INTO nobel VALUES ("2011","Peace","Leymah Gbowee");
INSERT INTO nobel VALUES ("2011","Peace","Tawakel Karman");
INSERT INTO nobel VALUES ("2011","Physics","Adam G. Riess");
INSERT INTO nobel VALUES ("2011","Physics","Brian Schmidt");
INSERT INTO nobel VALUES ("2011","Physics","Saul Perlmutter");
INSERT INTO nobel VALUES ("2010","Chemistry","Akira Suzuki");
INSERT INTO nobel VALUES ("2010","Chemistry","Ei-ichi Negishi");
INSERT INTO nobel VALUES ("2010","Chemistry","Richard F. Heck");
INSERT INTO nobel VALUES ("2010","Economics","Christopher A. Pissarides");
INSERT INTO nobel VALUES ("2010","Economics","Dale T. Mortensen");
INSERT INTO nobel VALUES ("2010","Economics","Peter A. Diamond");
INSERT INTO nobel VALUES ("2010","Literature","Mario Vargas Llosa");
INSERT INTO nobel VALUES ("2010","Medicine","Robert G. Edwards");
INSERT INTO nobel VALUES ("2010","Peace","Liu Xiaobo");
INSERT INTO nobel VALUES ("2010","Physics","Andre Geim");
INSERT INTO nobel VALUES ("2010","Physics","Konstantin Novoselov");
INSERT INTO nobel VALUES ("2009","Chemistry","Ada Yonath");
INSERT INTO nobel VALUES ("2009","Chemistry","Thomas A. Steitz");
INSERT INTO nobel VALUES ("2009","Chemistry","Venkatraman Ramakrishnan");
INSERT INTO nobel VALUES ("2009","Economics","Elinor Ostrom");
INSERT INTO nobel VALUES ("2009","Economics","Oliver E. Williamson");
INSERT INTO nobel VALUES ("2009","Literature","Herta Müller");
INSERT INTO nobel VALUES ("2009","Medicine","Carol W. Greider");
INSERT INTO nobel VALUES ("2009","Medicine","Elizabeth Blackburn");
INSERT INTO nobel VALUES ("2009","Medicine","Jack W. Szostak");
INSERT INTO nobel VALUES ("2009","Peace","Barack Obama");
INSERT INTO nobel VALUES ("2009","Physics","Charles K. Kao");
INSERT INTO nobel VALUES ("2009","Physics","George E. Smith");
INSERT INTO nobel VALUES ("2009","Physics","Willard S. Boyle");
INSERT INTO nobel VALUES ("2008","Chemistry","Martin Chalfie");
INSERT INTO nobel VALUES ("2008","Chemistry","Osamu Shimomura");
INSERT INTO nobel VALUES ("2008","Chemistry","Roger Y. Tsien");
INSERT INTO nobel VALUES ("2008","Economics","Paul Krugman");
INSERT INTO nobel VALUES ("2008","Literature","Jean-Marie Gustave Le Clézio");
INSERT INTO nobel VALUES ("2008","Medicine","Françoise Barré-Sinoussi");
INSERT INTO nobel VALUES ("2008","Medicine","Luc Montagnier");
INSERT INTO nobel VALUES ("2008","Medicine","Harald zur Hausen");
INSERT INTO nobel VALUES ("2008","Peace","Martti Ahtisaari");
INSERT INTO nobel VALUES ("2008","Physics","Makoto Kobayashi");
INSERT INTO nobel VALUES ("2008","Physics","Toshihide Maskawa");
INSERT INTO nobel VALUES ("2008","Physics","Yoichiro Nambu");
INSERT INTO nobel VALUES ("2007","Chemistry","Gerhard Ertl");
INSERT INTO nobel VALUES ("2007","Economics","Leonid Hurwicz");
INSERT INTO nobel VALUES ("2007","Economics","Eric S. Maskin");
INSERT INTO nobel VALUES ("2007","Economics","Roger B. Myerson");
INSERT INTO nobel VALUES ("2007","Literature","Doris Lessing");
INSERT INTO nobel VALUES ("2007","Medicine","Mario R. Capecchi");
INSERT INTO nobel VALUES ("2007","Medicine","Sir Martin J. Evans");
INSERT INTO nobel VALUES ("2007","Medicine","Oliver Smithies");
INSERT INTO nobel VALUES ("2007","Peace","Intergovernmental Panel on Climate Change");
INSERT INTO nobel VALUES ("2007","Peace","Al Gore");
INSERT INTO nobel VALUES ("2007","Physics","Albert Fert");
INSERT INTO nobel VALUES ("2007","Physics","Peter Grünberg");
INSERT INTO nobel VALUES ("2006","Chemistry","Roger D. Kornberg");
INSERT INTO nobel VALUES ("2006","Economics","Edmund S. Phelps");
INSERT INTO nobel VALUES ("2006","Literature","Orhan Pamuk");
INSERT INTO nobel VALUES ("2006","Medicine","Andrew Z. Fire");
INSERT INTO nobel VALUES ("2006","Medicine","Craig C. Mello");
INSERT INTO nobel VALUES ("2006","Peace","Grameen Bank");
INSERT INTO nobel VALUES ("2006","Peace","Muhammad Yunus");
INSERT INTO nobel VALUES ("2006","Physics","John C. Mather");
INSERT INTO nobel VALUES ("2006","Physics","George F. Smoot");
INSERT INTO nobel VALUES ("2005","Chemistry","Yves Chauvin");
INSERT INTO nobel VALUES ("2005","Chemistry","Robert H. Grubbs");
INSERT INTO nobel VALUES ("2005","Chemistry","Richard R. Schrock");
INSERT INTO nobel VALUES ("2005","Economics","Robert J. Aumann");
INSERT INTO nobel VALUES ("2005","Economics","Thomas C. Schelling");
INSERT INTO nobel VALUES ("2005","Literature","Harold Pinter");
INSERT INTO nobel VALUES ("2005","Medicine","Barry J. Marshall");
INSERT INTO nobel VALUES ("2005","Medicine","J. Robin Warren");
INSERT INTO nobel VALUES ("2005","Peace","International Atomic Energy Agency");
INSERT INTO nobel VALUES ("2005","Peace","Mohamed ElBaradei");
INSERT INTO nobel VALUES ("2005","Physics","Roy J. Glauber");
INSERT INTO nobel VALUES ("2005","Physics","John L. Hall");
INSERT INTO nobel VALUES ("2005","Physics","Theodor W. Hänsch");
INSERT INTO nobel VALUES ("2004","Chemistry","Aaron Ciechanover");
INSERT INTO nobel VALUES ("2004","Chemistry","Avram Hershko");
INSERT INTO nobel VALUES ("2004","Chemistry","Irwin Rose");
INSERT INTO nobel VALUES ("2004","Economics","Finn E. Kydland");
INSERT INTO nobel VALUES ("2004","Economics","Edward C. Prescott");
INSERT INTO nobel VALUES ("2004","Literature","Elfriede Jelinek");
INSERT INTO nobel VALUES ("2004","Medicine","Richard Axel");
INSERT INTO nobel VALUES ("2004","Medicine","Linda B. Buck");
INSERT INTO nobel VALUES ("2004","Peace","Wangari Maathai");
INSERT INTO nobel VALUES ("2004","Physics","David J. Gross");
INSERT INTO nobel VALUES ("2004","Physics","H. David Politzer");
INSERT INTO nobel VALUES ("2004","Physics","Frank Wilczek");
INSERT INTO nobel VALUES ("2003","Chemistry","Peter Agre");
INSERT INTO nobel VALUES ("2003","Chemistry","Roderick MacKinnon");
INSERT INTO nobel VALUES ("2003","Economics","Robert F. Engle III");
INSERT INTO nobel VALUES ("2003","Economics","Clive W.J. Granger");
INSERT INTO nobel VALUES ("2003","Literature","J. M. Coetzee");
INSERT INTO nobel VALUES ("2003","Medicine","Paul C. Lauterbur");
INSERT INTO nobel VALUES ("2003","Medicine","Sir Peter Mansfield");
INSERT INTO nobel VALUES ("2003","Peace","Shirin Ebadi");
INSERT INTO nobel VALUES ("2003","Physics","Alexei A. Abrikosov");
INSERT INTO nobel VALUES ("2003","Physics","Vitaly L. Ginzburg");
INSERT INTO nobel VALUES ("2003","Physics","Anthony J. Leggett");
INSERT INTO nobel VALUES ("2002","Chemistry","John B. Fenn");
INSERT INTO nobel VALUES ("2002","Chemistry","Koichi Tanaka");
INSERT INTO nobel VALUES ("2002","Chemistry","Kurt Wüthrich");
INSERT INTO nobel VALUES ("2002","Economics","Daniel Kahneman");
INSERT INTO nobel VALUES ("2002","Economics","Vernon L. Smith");
INSERT INTO nobel VALUES ("2002","Literature","Imre Kertész");
INSERT INTO nobel VALUES ("2002","Medicine","Sydney Brenner");
INSERT INTO nobel VALUES ("2002","Medicine","H. Robert Horvitz");
INSERT INTO nobel VALUES ("2002","Medicine","John E. Sulston");
INSERT INTO nobel VALUES ("2002","Peace","Jimmy Carter");
INSERT INTO nobel VALUES ("2002","Physics","Raymond Davis Jr.");
INSERT INTO nobel VALUES ("2002","Physics","Riccardo Giacconi");
INSERT INTO nobel VALUES ("2002","Physics","Masatoshi Koshiba");
INSERT INTO nobel VALUES ("2001","Chemistry","William S. Knowles");
INSERT INTO nobel VALUES ("2001","Chemistry","Ryoji Noyori");
INSERT INTO nobel VALUES ("2001","Chemistry","K. Barry Sharpless");
INSERT INTO nobel VALUES ("2001","Economics","George A. Akerlof");
INSERT INTO nobel VALUES ("2001","Economics","A. Michael Spence");
INSERT INTO nobel VALUES ("2001","Economics","Joseph E. Stiglitz");
INSERT INTO nobel VALUES ("2001","Literature","V. S. Naipaul");
INSERT INTO nobel VALUES ("2001","Medicine","Leland H. Hartwell");
INSERT INTO nobel VALUES ("2001","Medicine","Tim Hunt");
INSERT INTO nobel VALUES ("2001","Medicine","Sir Paul Nurse");
INSERT INTO nobel VALUES ("2001","Peace","United Nations");
INSERT INTO nobel VALUES ("2001","Peace","Kofi Annan");
INSERT INTO nobel VALUES ("2001","Physics","Eric A. Cornell");
INSERT INTO nobel VALUES ("2001","Physics","Wolfgang Ketterle");
INSERT INTO nobel VALUES ("2001","Physics","Carl E. Wieman");
INSERT INTO nobel VALUES ("2000","Chemistry","Alan Heeger");
INSERT INTO nobel VALUES ("2000","Chemistry","Alan G. MacDiarmid");
INSERT INTO nobel VALUES ("2000","Chemistry","Hideki Shirakawa");
INSERT INTO nobel VALUES ("2000","Economics","James J. Heckman");
INSERT INTO nobel VALUES ("2000","Economics","Daniel L. McFadden");
INSERT INTO nobel VALUES ("2000","Literature","Gao Xingjian");
INSERT INTO nobel VALUES ("2000","Medicine","Arvid Carlsson");
INSERT INTO nobel VALUES ("2000","Medicine","Paul Greengard");
INSERT INTO nobel VALUES ("2000","Medicine","Eric R. Kandel");
INSERT INTO nobel VALUES ("2000","Peace","Kim Dae-jung");
INSERT INTO nobel VALUES ("2000","Physics","Zhores I. Alferov");
INSERT INTO nobel VALUES ("2000","Physics","Jack S. Kilby");
INSERT INTO nobel VALUES ("2000","Physics","Herbert Kroemer");
INSERT INTO nobel VALUES ("1999","Chemistry","Ahmed Zewail");
INSERT INTO nobel VALUES ("1999","Economics","Robert A. Mundell");
INSERT INTO nobel VALUES ("1999","Literature","Günter Grass");
INSERT INTO nobel VALUES ("1999","Medicine","Günter Blobel");
INSERT INTO nobel VALUES ("1999","Peace","Médecins Sans Frontières");
INSERT INTO nobel VALUES ("1999","Physics","Gerardus 't Hooft");
INSERT INTO nobel VALUES ("1999","Physics","Martinus J.G. Veltman");
INSERT INTO nobel VALUES ("1998","Chemistry","Walter Kohn");
INSERT INTO nobel VALUES ("1998","Chemistry","John Pople");
INSERT INTO nobel VALUES ("1998","Economics","Amartya Sen");
INSERT INTO nobel VALUES ("1998","Literature","José Saramago");
INSERT INTO nobel VALUES ("1998","Medicine","Robert F. Furchgott");
INSERT INTO nobel VALUES ("1998","Medicine","Louis J. Ignarro");
INSERT INTO nobel VALUES ("1998","Medicine","Ferid Murad");
INSERT INTO nobel VALUES ("1998","Peace","John Hume");
INSERT INTO nobel VALUES ("1998","Peace","David Trimble");
INSERT INTO nobel VALUES ("1998","Physics","Robert B. Laughlin");
INSERT INTO nobel VALUES ("1998","Physics","Horst L. Störmer");
INSERT INTO nobel VALUES ("1998","Physics","Daniel C. Tsui");
INSERT INTO nobel VALUES ("1997","Chemistry","Paul D. Boyer");
INSERT INTO nobel VALUES ("1997","Chemistry","Jens C. Skou");
INSERT INTO nobel VALUES ("1997","Chemistry","John E. Walker");
INSERT INTO nobel VALUES ("1997","Economics","Robert C. Merton");
INSERT INTO nobel VALUES ("1997","Economics","Myron S. Scholes");
INSERT INTO nobel VALUES ("1997","Literature","Dario Fo");
INSERT INTO nobel VALUES ("1997","Medicine","Stanley B. Prusiner");
INSERT INTO nobel VALUES ("1997","Peace","International Campaign to Ban Landmines");
INSERT INTO nobel VALUES ("1997","Peace","Jody Williams");
INSERT INTO nobel VALUES ("1997","Physics","Steven Chu");
INSERT INTO nobel VALUES ("1997","Physics","Claude Cohen-Tannoudji");
INSERT INTO nobel VALUES ("1997","Physics","William D. Phillips");
INSERT INTO nobel VALUES ("1996","Chemistry","Robert F. Curl Jr.");
INSERT INTO nobel VALUES ("1996","Chemistry","Sir Harold Kroto");
INSERT INTO nobel VALUES ("1996","Chemistry","Richard E. Smalley");
INSERT INTO nobel VALUES ("1996","Economics","James A. Mirrlees");
INSERT INTO nobel VALUES ("1996","Economics","William Vickrey");
INSERT INTO nobel VALUES ("1996","Literature","Wislawa Szymborska");
INSERT INTO nobel VALUES ("1996","Medicine","Peter C. Doherty");
INSERT INTO nobel VALUES ("1996","Medicine","Rolf M. Zinkernagel");
INSERT INTO nobel VALUES ("1996","Peace","Carlos Filipe Ximenes Belo");
INSERT INTO nobel VALUES ("1996","Peace","José Ramos-Horta");
INSERT INTO nobel VALUES ("1996","Physics","David M. Lee");
INSERT INTO nobel VALUES ("1996","Physics","Douglas D. Osheroff");
INSERT INTO nobel VALUES ("1996","Physics","Robert C. Richardson");
INSERT INTO nobel VALUES ("1995","Chemistry","Paul J. Crutzen");
INSERT INTO nobel VALUES ("1995","Chemistry","Mario J. Molina");
INSERT INTO nobel VALUES ("1995","Chemistry","F. Sherwood Rowland");
INSERT INTO nobel VALUES ("1995","Economics","Robert E. Lucas Jr.");
INSERT INTO nobel VALUES ("1995","Literature","Seamus Heaney");
INSERT INTO nobel VALUES ("1995","Medicine","Edward B. Lewis");
INSERT INTO nobel VALUES ("1995","Medicine","Christiane Nüsslein-Volhard");
INSERT INTO nobel VALUES ("1995","Medicine","Eric F. Wieschaus");
INSERT INTO nobel VALUES ("1995","Peace","Pugwash Conferences on Science and World Affairs");
INSERT INTO nobel VALUES ("1995","Peace","Joseph Rotblat");
INSERT INTO nobel VALUES ("1995","Physics","Martin L. Perl");
INSERT INTO nobel VALUES ("1995","Physics","Frederick Reines");
INSERT INTO nobel VALUES ("1994","Chemistry","George A. Olah");
INSERT INTO nobel VALUES ("1994","Economics","John C. Harsanyi");
INSERT INTO nobel VALUES ("1994","Economics","John F. Nash Jr.");
INSERT INTO nobel VALUES ("1994","Economics","Reinhard Selten");
INSERT INTO nobel VALUES ("1994","Literature","Kenzaburo Oe");
INSERT INTO nobel VALUES ("1994","Medicine","Alfred G. Gilman");
INSERT INTO nobel VALUES ("1994","Medicine","Martin Rodbell");
INSERT INTO nobel VALUES ("1994","Peace","Yasser Arafat");
INSERT INTO nobel VALUES ("1994","Peace","Shimon Peres");
INSERT INTO nobel VALUES ("1994","Peace","Yitzhak Rabin");
INSERT INTO nobel VALUES ("1994","Physics","Bertram N. Brockhouse");
INSERT INTO nobel VALUES ("1994","Physics","Clifford G. Shull");
INSERT INTO nobel VALUES ("1993","Chemistry","Kary B. Mullis");
INSERT INTO nobel VALUES ("1993","Chemistry","Michael Smith");
INSERT INTO nobel VALUES ("1993","Economics","Robert W. Fogel");
INSERT INTO nobel VALUES ("1993","Economics","Douglass C. North");
INSERT INTO nobel VALUES ("1993","Literature","Toni Morrison");
INSERT INTO nobel VALUES ("1993","Medicine","Richard J. Roberts");
INSERT INTO nobel VALUES ("1993","Medicine","Phillip A. Sharp");
INSERT INTO nobel VALUES ("1993","Peace","F.W. de Klerk");
INSERT INTO nobel VALUES ("1993","Peace","Nelson Mandela");
INSERT INTO nobel VALUES ("1993","Physics","Russell A. Hulse");
INSERT INTO nobel VALUES ("1993","Physics","Joseph H. Taylor Jr.");
INSERT INTO nobel VALUES ("1992","Chemistry","Rudolph A. Marcus");
INSERT INTO nobel VALUES ("1992","Economics","Gary S. Becker");
INSERT INTO nobel VALUES ("1992","Literature","Derek Walcott");
INSERT INTO nobel VALUES ("1992","Medicine","Edmond H. Fischer");
INSERT INTO nobel VALUES ("1992","Medicine","Edwin G. Krebs");
INSERT INTO nobel VALUES ("1992","Peace","Rigoberta Menchú Tum");
INSERT INTO nobel VALUES ("1992","Physics","Georges Charpak");
INSERT INTO nobel VALUES ("1991","Chemistry","Richard R. Ernst");
INSERT INTO nobel VALUES ("1991","Economics","Ronald H. Coase");
INSERT INTO nobel VALUES ("1991","Literature","Nadine Gordimer");
INSERT INTO nobel VALUES ("1991","Medicine","Erwin Neher");
INSERT INTO nobel VALUES ("1991","Medicine","Bert Sakmann");
INSERT INTO nobel VALUES ("1991","Peace","Aung San Suu Kyi");
INSERT INTO nobel VALUES ("1991","Physics","Pierre-Gilles de Gennes");
INSERT INTO nobel VALUES ("1990","Chemistry","Elias James Corey");
INSERT INTO nobel VALUES ("1990","Economics","Harry M. Markowitz");
INSERT INTO nobel VALUES ("1990","Economics","Merton H. Miller");
INSERT INTO nobel VALUES ("1990","Economics","William F. Sharpe");
INSERT INTO nobel VALUES ("1990","Literature","Octavio Paz");
INSERT INTO nobel VALUES ("1990","Medicine","Joseph E. Murray");
INSERT INTO nobel VALUES ("1990","Medicine","E. Donnall Thomas");
INSERT INTO nobel VALUES ("1990","Peace","Mikhail Gorbachev");
INSERT INTO nobel VALUES ("1990","Physics","Jerome I. Friedman");
INSERT INTO nobel VALUES ("1990","Physics","Henry W. Kendall");
INSERT INTO nobel VALUES ("1990","Physics","Richard E. Taylor");
INSERT INTO nobel VALUES ("1989","Chemistry","Sidney Altman");
INSERT INTO nobel VALUES ("1989","Chemistry","Thomas R. Cech");
INSERT INTO nobel VALUES ("1989","Economics","Trygve Haavelmo");
INSERT INTO nobel VALUES ("1989","Literature","Camilo José Cela");
INSERT INTO nobel VALUES ("1989","Medicine","J. Michael Bishop");
INSERT INTO nobel VALUES ("1989","Medicine","Harold E. Varmus");
INSERT INTO nobel VALUES ("1989","Peace","The 14th Dalai Lama");
INSERT INTO nobel VALUES ("1989","Physics","Hans G. Dehmelt");
INSERT INTO nobel VALUES ("1989","Physics","Wolfgang Paul");
INSERT INTO nobel VALUES ("1989","Physics","Norman F. Ramsey");
INSERT INTO nobel VALUES ("1988","Chemistry","Johann Deisenhofer");
INSERT INTO nobel VALUES ("1988","Chemistry","Robert Huber");
INSERT INTO nobel VALUES ("1988","Chemistry","Hartmut Michel");
INSERT INTO nobel VALUES ("1988","Economics","Maurice Allais");
INSERT INTO nobel VALUES ("1988","Literature","Naguib Mahfouz");
INSERT INTO nobel VALUES ("1988","Medicine","Sir James W. Black");
INSERT INTO nobel VALUES ("1988","Medicine","Gertrude B. Elion");
INSERT INTO nobel VALUES ("1988","Medicine","George H. Hitchings");
INSERT INTO nobel VALUES ("1988","Peace","United Nations Peacekeeping Forces");
INSERT INTO nobel VALUES ("1988","Physics","Leon M. Lederman");
INSERT INTO nobel VALUES ("1988","Physics","Melvin Schwartz");
INSERT INTO nobel VALUES ("1988","Physics","Jack Steinberger");
INSERT INTO nobel VALUES ("1987","Chemistry","Donald J. Cram");
INSERT INTO nobel VALUES ("1987","Chemistry","Jean-Marie Lehn");
INSERT INTO nobel VALUES ("1987","Chemistry","Charles J. Pedersen");
INSERT INTO nobel VALUES ("1987","Economics","Robert M. Solow");
INSERT INTO nobel VALUES ("1987","Literature","Joseph Brodsky");
INSERT INTO nobel VALUES ("1987","Medicine","Susumu Tonegawa");
INSERT INTO nobel VALUES ("1987","Peace","Oscar Arias Sánchez");
INSERT INTO nobel VALUES ("1987","Physics","J. Georg Bednorz");
INSERT INTO nobel VALUES ("1987","Physics","K. Alex Müller");
INSERT INTO nobel VALUES ("1986","Chemistry","Dudley R. Herschbach");
INSERT INTO nobel VALUES ("1986","Chemistry","Yuan T. Lee");
INSERT INTO nobel VALUES ("1986","Chemistry","John C. Polanyi");
INSERT INTO nobel VALUES ("1986","Economics","James M. Buchanan Jr.");
INSERT INTO nobel VALUES ("1986","Literature","Wole Soyinka");
INSERT INTO nobel VALUES ("1986","Medicine","Stanley Cohen");
INSERT INTO nobel VALUES ("1986","Medicine","Rita Levi-Montalcini");
INSERT INTO nobel VALUES ("1986","Peace","Elie Wiesel");
INSERT INTO nobel VALUES ("1986","Physics","Gerd Binnig");
INSERT INTO nobel VALUES ("1986","Physics","Heinrich Rohrer");
INSERT INTO nobel VALUES ("1986","Physics","Ernst Ruska");
INSERT INTO nobel VALUES ("1985","Chemistry","Herbert A. Hauptman");
INSERT INTO nobel VALUES ("1985","Chemistry","Jerome Karle");
INSERT INTO nobel VALUES ("1985","Economics","Franco Modigliani");
INSERT INTO nobel VALUES ("1985","Literature","Claude Simon");
INSERT INTO nobel VALUES ("1985","Medicine","Michael S. Brown");
INSERT INTO nobel VALUES ("1985","Medicine","Joseph L. Goldstein");
INSERT INTO nobel VALUES ("1985","Physics","Klaus von Klitzing");
INSERT INTO nobel VALUES ("1984","Chemistry","Bruce Merrifield");
INSERT INTO nobel VALUES ("1984","Economics","Richard Stone");
INSERT INTO nobel VALUES ("1984","Literature","Jaroslav Seifert");
INSERT INTO nobel VALUES ("1984","Medicine","Niels K. Jerne");
INSERT INTO nobel VALUES ("1984","Medicine","Georges J.F. Köhler");
INSERT INTO nobel VALUES ("1984","Medicine","César Milstein");
INSERT INTO nobel VALUES ("1984","Peace","Desmond Tutu");
INSERT INTO nobel VALUES ("1984","Physics","Carlo Rubbia");
INSERT INTO nobel VALUES ("1984","Physics","Simon van der Meer");
INSERT INTO nobel VALUES ("1983","Chemistry","Henry Taube");
INSERT INTO nobel VALUES ("1983","Economics","Gerard Debreu");
INSERT INTO nobel VALUES ("1983","Literature","William Golding");
INSERT INTO nobel VALUES ("1983","Medicine","Barbara McClintock");
INSERT INTO nobel VALUES ("1983","Peace","Lech Walesa");
INSERT INTO nobel VALUES ("1983","Physics","Subramanyan Chandrasekhar");
INSERT INTO nobel VALUES ("1983","Physics","William A. Fowler");
INSERT INTO nobel VALUES ("1982","Chemistry","Aaron Klug");
INSERT INTO nobel VALUES ("1982","Economics","George J. Stigler");
INSERT INTO nobel VALUES ("1982","Literature","Gabriel García Márquez");
INSERT INTO nobel VALUES ("1982","Medicine","Sune K. Bergström");
INSERT INTO nobel VALUES ("1982","Medicine","Bengt I. Samuelsson");
INSERT INTO nobel VALUES ("1982","Medicine","John R. Vane");
INSERT INTO nobel VALUES ("1982","Peace","Alfonso García Robles");
INSERT INTO nobel VALUES ("1982","Peace","Alva Myrdal");
INSERT INTO nobel VALUES ("1982","Physics","Kenneth G. Wilson");
INSERT INTO nobel VALUES ("1981","Chemistry","Kenichi Fukui");
INSERT INTO nobel VALUES ("1981","Chemistry","Roald Hoffmann");
INSERT INTO nobel VALUES ("1981","Economics","James Tobin");
INSERT INTO nobel VALUES ("1981","Literature","Elias Canetti");
INSERT INTO nobel VALUES ("1981","Medicine","David H. Hubel");
INSERT INTO nobel VALUES ("1981","Medicine","Roger W. Sperry");
INSERT INTO nobel VALUES ("1981","Medicine","Torsten N. Wiesel");
INSERT INTO nobel VALUES ("1981","Physics","Nicolaas Bloembergen");
INSERT INTO nobel VALUES ("1981","Physics","Arthur L. Schawlow");
INSERT INTO nobel VALUES ("1981","Physics","Kai M. Siegbahn");
INSERT INTO nobel VALUES ("1980","Chemistry","Paul Berg");
INSERT INTO nobel VALUES ("1980","Chemistry","Walter Gilbert");
INSERT INTO nobel VALUES ("1980","Chemistry","Frederick Sanger");
INSERT INTO nobel VALUES ("1980","Economics","Lawrence R. Klein");
INSERT INTO nobel VALUES ("1980","Literature","Czeslaw Milosz");
INSERT INTO nobel VALUES ("1980","Medicine","Baruj Benacerraf");
INSERT INTO nobel VALUES ("1980","Medicine","Jean Dausset");
INSERT INTO nobel VALUES ("1980","Medicine","George D. Snell");
INSERT INTO nobel VALUES ("1980","Peace","Adolfo Pérez Esquivel");
INSERT INTO nobel VALUES ("1980","Physics","James Cronin");
INSERT INTO nobel VALUES ("1980","Physics","Val Fitch");
INSERT INTO nobel VALUES ("1979","Chemistry","Herbert C. Brown");
INSERT INTO nobel VALUES ("1979","Chemistry","Georg Wittig");
INSERT INTO nobel VALUES ("1979","Economics","Sir Arthur Lewis");
INSERT INTO nobel VALUES ("1979","Economics","Theodore W. Schultz");
INSERT INTO nobel VALUES ("1979","Literature","Odysseus Elytis");
INSERT INTO nobel VALUES ("1979","Medicine","Allan M. Cormack");
INSERT INTO nobel VALUES ("1979","Medicine","Godfrey N. Hounsfield");
INSERT INTO nobel VALUES ("1979","Peace","Mother Teresa");
INSERT INTO nobel VALUES ("1979","Physics","Sheldon Glashow");
INSERT INTO nobel VALUES ("1979","Physics","Abdus Salam");
INSERT INTO nobel VALUES ("1979","Physics","Steven Weinberg");
INSERT INTO nobel VALUES ("1978","Chemistry","Peter Mitchell");
INSERT INTO nobel VALUES ("1978","Economics","Herbert A. Simon");
INSERT INTO nobel VALUES ("1978","Literature","Isaac Bashevis Singer");
INSERT INTO nobel VALUES ("1978","Medicine","Werner Arber");
INSERT INTO nobel VALUES ("1978","Medicine","Daniel Nathans");
INSERT INTO nobel VALUES ("1978","Medicine","Hamilton O. Smith");
INSERT INTO nobel VALUES ("1978","Peace","Anwar al-Sadat");
INSERT INTO nobel VALUES ("1978","Peace","Menachem Begin");
INSERT INTO nobel VALUES ("1978","Physics","Pyotr Kapitsa");
INSERT INTO nobel VALUES ("1978","Physics","Arno Penzias");
INSERT INTO nobel VALUES ("1978","Physics","Robert Woodrow Wilson");
INSERT INTO nobel VALUES ("1977","Chemistry","Ilya Prigogine");
INSERT INTO nobel VALUES ("1977","Economics","James E. Meade");
INSERT INTO nobel VALUES ("1977","Economics","Bertil Ohlin");
INSERT INTO nobel VALUES ("1977","Literature","Vicente Aleixandre");
INSERT INTO nobel VALUES ("1977","Medicine","Roger Guillemin");
INSERT INTO nobel VALUES ("1977","Medicine","Andrew V. Schally");
INSERT INTO nobel VALUES ("1977","Medicine","Rosalyn Yalow");
INSERT INTO nobel VALUES ("1977","Peace","Amnesty International");
INSERT INTO nobel VALUES ("1977","Physics","Philip W. Anderson");
INSERT INTO nobel VALUES ("1977","Physics","Sir Nevill F. Mott");
INSERT INTO nobel VALUES ("1977","Physics","John H. van Vleck");
INSERT INTO nobel VALUES ("1976","Chemistry","William Lipscomb");
INSERT INTO nobel VALUES ("1976","Economics","Milton Friedman");
INSERT INTO nobel VALUES ("1976","Literature","Saul Bellow");
INSERT INTO nobel VALUES ("1976","Medicine","Baruch S. Blumberg");
INSERT INTO nobel VALUES ("1976","Medicine","D. Carleton Gajdusek");
INSERT INTO nobel VALUES ("1976","Peace","Mairead Corrigan");
INSERT INTO nobel VALUES ("1976","Peace","Betty Williams");
INSERT INTO nobel VALUES ("1976","Physics","Burton Richter");
INSERT INTO nobel VALUES ("1976","Physics","Samuel C.C. Ting");
INSERT INTO nobel VALUES ("1975","Chemistry","John Cornforth");
INSERT INTO nobel VALUES ("1975","Chemistry","Vladimir Prelog");
INSERT INTO nobel VALUES ("1975","Economics","Leonid Vitaliyevich Kantorovich");
INSERT INTO nobel VALUES ("1975","Economics","Tjalling C. Koopmans");
INSERT INTO nobel VALUES ("1975","Literature","Eugenio Montale");
INSERT INTO nobel VALUES ("1975","Medicine","David Baltimore");
INSERT INTO nobel VALUES ("1975","Medicine","Renato Dulbecco");
INSERT INTO nobel VALUES ("1975","Medicine","Howard M. Temin");
INSERT INTO nobel VALUES ("1975","Peace","Andrei Sakharov");
INSERT INTO nobel VALUES ("1975","Physics","Aage N. Bohr");
INSERT INTO nobel VALUES ("1975","Physics","Ben R. Mottelson");
INSERT INTO nobel VALUES ("1975","Physics","James Rainwater");
INSERT INTO nobel VALUES ("1974","Chemistry","Paul J. Flory");
INSERT INTO nobel VALUES ("1974","Economics","Gunnar Myrdal");
INSERT INTO nobel VALUES ("1974","Economics","Friedrich August von Hayek");
INSERT INTO nobel VALUES ("1974","Literature","Eyvind Johnson");
INSERT INTO nobel VALUES ("1974","Literature","Harry Martinson");
INSERT INTO nobel VALUES ("1974","Medicine","Albert Claude");
INSERT INTO nobel VALUES ("1974","Medicine","Christian de Duve");
INSERT INTO nobel VALUES ("1974","Medicine","George E. Palade");
INSERT INTO nobel VALUES ("1974","Peace","Seán MacBride");
INSERT INTO nobel VALUES ("1974","Peace","Eisaku Sato");
INSERT INTO nobel VALUES ("1974","Physics","Antony Hewish");
INSERT INTO nobel VALUES ("1974","Physics","Martin Ryle");
INSERT INTO nobel VALUES ("1973","Chemistry","Ernst Otto Fischer");
INSERT INTO nobel VALUES ("1973","Chemistry","Geoffrey Wilkinson");
INSERT INTO nobel VALUES ("1973","Economics","Wassily Leontief");
INSERT INTO nobel VALUES ("1973","Literature","Patrick White");
INSERT INTO nobel VALUES ("1973","Medicine","Konrad Lorenz");
INSERT INTO nobel VALUES ("1973","Medicine","Nikolaas Tinbergen");
INSERT INTO nobel VALUES ("1973","Medicine","Karl von Frisch");
INSERT INTO nobel VALUES ("1973","Peace","Le Duc Tho");
INSERT INTO nobel VALUES ("1973","Peace","Henry Kissinger");
INSERT INTO nobel VALUES ("1973","Physics","Leo Esaki");
INSERT INTO nobel VALUES ("1973","Physics","Ivar Giaever");
INSERT INTO nobel VALUES ("1973","Physics","Brian D. Josephson");
INSERT INTO nobel VALUES ("1972","Chemistry","Christian Anfinsen");
INSERT INTO nobel VALUES ("1972","Chemistry","Stanford Moore");
INSERT INTO nobel VALUES ("1972","Chemistry","William H. Stein");
INSERT INTO nobel VALUES ("1972","Economics","Kenneth J. Arrow");
INSERT INTO nobel VALUES ("1972","Economics","John R. Hicks");
INSERT INTO nobel VALUES ("1972","Literature","Heinrich Böll");
INSERT INTO nobel VALUES ("1972","Medicine","Gerald M. Edelman");
INSERT INTO nobel VALUES ("1972","Medicine","Rodney R. Porter");
INSERT INTO nobel VALUES ("1972","Physics","John Bardeen");
INSERT INTO nobel VALUES ("1972","Physics","Leon N. Cooper");
INSERT INTO nobel VALUES ("1972","Physics","Robert Schrieffer");
INSERT INTO nobel VALUES ("1971","Chemistry","Gerhard Herzberg");
INSERT INTO nobel VALUES ("1971","Economics","Simon Kuznets");
INSERT INTO nobel VALUES ("1971","Literature","Pablo Neruda");
INSERT INTO nobel VALUES ("1971","Medicine","Earl W. Sutherland, Jr.");
INSERT INTO nobel VALUES ("1971","Peace","Willy Brandt");
INSERT INTO nobel VALUES ("1971","Physics","Dennis Gabor");
INSERT INTO nobel VALUES ("1970","Chemistry","Luis Leloir");
INSERT INTO nobel VALUES ("1970","Economics","Paul A. Samuelson");
INSERT INTO nobel VALUES ("1970","Literature","Alexandr Solzhenitsyn");
INSERT INTO nobel VALUES ("1970","Medicine","Julius Axelrod");
INSERT INTO nobel VALUES ("1970","Medicine","Sir Bernard Katz");
INSERT INTO nobel VALUES ("1970","Medicine","Ulf von Euler");
INSERT INTO nobel VALUES ("1970","Peace","Norman Borlaug");
INSERT INTO nobel VALUES ("1970","Physics","Hannes Alfvén");
INSERT INTO nobel VALUES ("1970","Physics","Louis Néel");
INSERT INTO nobel VALUES ("1969","Chemistry","Derek Barton");
INSERT INTO nobel VALUES ("1969","Chemistry","Odd Hassel");
INSERT INTO nobel VALUES ("1969","Economics","Ragnar Frisch");
INSERT INTO nobel VALUES ("1969","Economics","Jan Tinbergen");
INSERT INTO nobel VALUES ("1969","Literature","Samuel Beckett");
INSERT INTO nobel VALUES ("1969","Medicine","Max Delbrück");
INSERT INTO nobel VALUES ("1969","Medicine","Alfred D. Hershey");
INSERT INTO nobel VALUES ("1969","Medicine","Salvador E. Luria");
INSERT INTO nobel VALUES ("1969","Peace","International Labour Organization");
INSERT INTO nobel VALUES ("1969","Physics","Murray Gell-Mann");
INSERT INTO nobel VALUES ("1968","Chemistry","Lars Onsager");
INSERT INTO nobel VALUES ("1968","Literature","Yasunari Kawabata");
INSERT INTO nobel VALUES ("1968","Medicine","Robert W. Holley");
INSERT INTO nobel VALUES ("1968","Medicine","H. Gobind Khorana");
INSERT INTO nobel VALUES ("1968","Medicine","Marshall W. Nirenberg");
INSERT INTO nobel VALUES ("1968","Peace","René Cassin");
INSERT INTO nobel VALUES ("1968","Physics","Luis Alvarez");
INSERT INTO nobel VALUES ("1967","Chemistry","Manfred Eigen");
INSERT INTO nobel VALUES ("1967","Chemistry","Ronald G.W. Norrish");
INSERT INTO nobel VALUES ("1967","Chemistry","George Porter");
INSERT INTO nobel VALUES ("1967","Literature","Miguel Angel Asturias");
INSERT INTO nobel VALUES ("1967","Medicine","Ragnar Granit");
INSERT INTO nobel VALUES ("1967","Medicine","Haldan K. Hartline");
INSERT INTO nobel VALUES ("1967","Medicine","George Wald");
INSERT INTO nobel VALUES ("1967","Physics","Hans Bethe");
INSERT INTO nobel VALUES ("1966","Chemistry","Robert S. Mulliken");
INSERT INTO nobel VALUES ("1966","Literature","Shmuel Agnon");
INSERT INTO nobel VALUES ("1966","Literature","Nelly Sachs");
INSERT INTO nobel VALUES ("1966","Medicine","Charles B. Huggins");
INSERT INTO nobel VALUES ("1966","Medicine","Peyton Rous");
INSERT INTO nobel VALUES ("1966","Physics","Alfred Kastler");
INSERT INTO nobel VALUES ("1965","Chemistry","Robert B. Woodward");
INSERT INTO nobel VALUES ("1965","Literature","Mikhail Sholokhov");
INSERT INTO nobel VALUES ("1965","Medicine","François Jacob");
INSERT INTO nobel VALUES ("1965","Medicine","André Lwoff");
INSERT INTO nobel VALUES ("1965","Medicine","Jacques Monod");
INSERT INTO nobel VALUES ("1965","Peace","United Nations Children's Fund");
INSERT INTO nobel VALUES ("1965","Physics","Richard P. Feynman");
INSERT INTO nobel VALUES ("1965","Physics","Julian Schwinger");
INSERT INTO nobel VALUES ("1965","Physics","Sin-Itiro Tomonaga");
INSERT INTO nobel VALUES ("1964","Chemistry","Dorothy Crowfoot Hodgkin");
INSERT INTO nobel VALUES ("1964","Literature","Jean-Paul Sartre");
INSERT INTO nobel VALUES ("1964","Medicine","Konrad Bloch");
INSERT INTO nobel VALUES ("1964","Medicine","Feodor Lynen");
INSERT INTO nobel VALUES ("1964","Peace","Martin Luther King Jr.");
INSERT INTO nobel VALUES ("1964","Physics","Nicolay G. Basov");
INSERT INTO nobel VALUES ("1964","Physics","Aleksandr M. Prokhorov");
INSERT INTO nobel VALUES ("1964","Physics","Charles H. Townes");
INSERT INTO nobel VALUES ("1963","Chemistry","Giulio Natta");
INSERT INTO nobel VALUES ("1963","Chemistry","Karl Ziegler");
INSERT INTO nobel VALUES ("1963","Literature","Giorgos Seferis");
INSERT INTO nobel VALUES ("1963","Medicine","Sir John Eccles");
INSERT INTO nobel VALUES ("1963","Medicine","Alan L. Hodgkin");
INSERT INTO nobel VALUES ("1963","Medicine","Andrew F. Huxley");
INSERT INTO nobel VALUES ("1963","Peace","International Committee of the Red Cross");
INSERT INTO nobel VALUES ("1963","Peace","League of Red Cross Societies");
INSERT INTO nobel VALUES ("1963","Physics","Maria Goeppert-Mayer");
INSERT INTO nobel VALUES ("1963","Physics","J. Hans D. Jensen");
INSERT INTO nobel VALUES ("1963","Physics","Eugene Wigner");
INSERT INTO nobel VALUES ("1962","Chemistry","John C. Kendrew");
INSERT INTO nobel VALUES ("1962","Chemistry","Max F. Perutz");
INSERT INTO nobel VALUES ("1962","Literature","John Steinbeck");
INSERT INTO nobel VALUES ("1962","Medicine","Francis Crick");
INSERT INTO nobel VALUES ("1962","Medicine","James Watson");
INSERT INTO nobel VALUES ("1962","Medicine","Maurice Wilkins");
INSERT INTO nobel VALUES ("1962","Peace","Linus Pauling");
INSERT INTO nobel VALUES ("1962","Physics","Lev Landau");
INSERT INTO nobel VALUES ("1961","Chemistry","Melvin Calvin");
INSERT INTO nobel VALUES ("1961","Literature","Ivo Andric");
INSERT INTO nobel VALUES ("1961","Medicine","Georg von Békésy");
INSERT INTO nobel VALUES ("1961","Peace","Dag Hammarskjöld");
INSERT INTO nobel VALUES ("1961","Physics","Robert Hofstadter");
INSERT INTO nobel VALUES ("1961","Physics","Rudolf Mössbauer");
INSERT INTO nobel VALUES ("1960","Chemistry","Willard F. Libby");
INSERT INTO nobel VALUES ("1960","Literature","Saint-John Perse");
INSERT INTO nobel VALUES ("1960","Medicine","Sir Frank Macfarlane Burnet");
INSERT INTO nobel VALUES ("1960","Medicine","Peter Medawar");
INSERT INTO nobel VALUES ("1960","Peace","Albert Lutuli");
INSERT INTO nobel VALUES ("1960","Physics","Donald A. Glaser");
INSERT INTO nobel VALUES ("1959","Chemistry","Jaroslav Heyrovsky");
INSERT INTO nobel VALUES ("1959","Literature","Salvatore Quasimodo");
INSERT INTO nobel VALUES ("1959","Medicine","Arthur Kornberg");
INSERT INTO nobel VALUES ("1959","Medicine","Severo Ochoa");
INSERT INTO nobel VALUES ("1959","Peace","Philip Noel-Baker");
INSERT INTO nobel VALUES ("1959","Physics","Owen Chamberlain");
INSERT INTO nobel VALUES ("1959","Physics","Emilio Segrè");
INSERT INTO nobel VALUES ("1958","Chemistry","Frederick Sanger");
INSERT INTO nobel VALUES ("1958","Literature","Boris Pasternak");
INSERT INTO nobel VALUES ("1958","Medicine","George Beadle");
INSERT INTO nobel VALUES ("1958","Medicine","Joshua Lederberg");
INSERT INTO nobel VALUES ("1958","Medicine","Edward Tatum");
INSERT INTO nobel VALUES ("1958","Peace","Georges Pire");
INSERT INTO nobel VALUES ("1958","Physics","Pavel A. Cherenkov");
INSERT INTO nobel VALUES ("1958","Physics","Il´ja M. Frank");
INSERT INTO nobel VALUES ("1958","Physics","Igor Y. Tamm");
INSERT INTO nobel VALUES ("1957","Chemistry","Lord Todd");
INSERT INTO nobel VALUES ("1957","Literature","Albert Camus");
INSERT INTO nobel VALUES ("1957","Medicine","Daniel Bovet");
INSERT INTO nobel VALUES ("1957","Peace","Lester Bowles Pearson");
INSERT INTO nobel VALUES ("1957","Physics","Tsung-Dao Lee");
INSERT INTO nobel VALUES ("1957","Physics","Chen Ning Yang");
INSERT INTO nobel VALUES ("1956","Chemistry","Sir Cyril Hinshelwood");
INSERT INTO nobel VALUES ("1956","Chemistry","Nikolay Semenov");
INSERT INTO nobel VALUES ("1956","Literature","Juan Ramón Jiménez");
INSERT INTO nobel VALUES ("1956","Medicine","André F. Cournand");
INSERT INTO nobel VALUES ("1956","Medicine","Werner Forssmann");
INSERT INTO nobel VALUES ("1956","Medicine","Dickinson W. Richards");
INSERT INTO nobel VALUES ("1956","Physics","John Bardeen");
INSERT INTO nobel VALUES ("1956","Physics","Walter H. Brattain");
INSERT INTO nobel VALUES ("1956","Physics","William B. Shockley");
INSERT INTO nobel VALUES ("1955","Chemistry","Vincent du Vigneaud");
INSERT INTO nobel VALUES ("1955","Literature","Halldór Laxness");
INSERT INTO nobel VALUES ("1955","Medicine","Hugo Theorell");
INSERT INTO nobel VALUES ("1955","Physics","Polykarp Kusch");
INSERT INTO nobel VALUES ("1955","Physics","Willis E. Lamb");
INSERT INTO nobel VALUES ("1954","Chemistry","Linus Pauling");
INSERT INTO nobel VALUES ("1954","Literature","Ernest Hemingway");
INSERT INTO nobel VALUES ("1954","Medicine","John F. Enders");
INSERT INTO nobel VALUES ("1954","Medicine","Frederick C. Robbins");
INSERT INTO nobel VALUES ("1954","Medicine","Thomas H. Weller");
INSERT INTO nobel VALUES ("1954","Physics","Max Born");
INSERT INTO nobel VALUES ("1954","Physics","Walther Bothe");
INSERT INTO nobel VALUES ("1953","Chemistry","Hermann Staudinger");
INSERT INTO nobel VALUES ("1953","Literature","Winston Churchill");
INSERT INTO nobel VALUES ("1953","Medicine","Hans Krebs");
INSERT INTO nobel VALUES ("1953","Medicine","Fritz Lipmann");
INSERT INTO nobel VALUES ("1953","Peace","George C. Marshall");
INSERT INTO nobel VALUES ("1953","Physics","Frits Zernike");
INSERT INTO nobel VALUES ("1952","Chemistry","Archer J.P. Martin");
INSERT INTO nobel VALUES ("1952","Chemistry","Richard L.M. Synge");
INSERT INTO nobel VALUES ("1952","Literature","François Mauriac");
INSERT INTO nobel VALUES ("1952","Medicine","Selman A. Waksman");
INSERT INTO nobel VALUES ("1952","Peace","Albert Schweitzer");
INSERT INTO nobel VALUES ("1952","Physics","Felix Bloch");
INSERT INTO nobel VALUES ("1952","Physics","E. M. Purcell");
INSERT INTO nobel VALUES ("1951","Chemistry","Edwin M. McMillan");
INSERT INTO nobel VALUES ("1951","Chemistry","Glenn T. Seaborg");
INSERT INTO nobel VALUES ("1951","Literature","Pär Lagerkvist");
INSERT INTO nobel VALUES ("1951","Medicine","Max Theiler");
INSERT INTO nobel VALUES ("1951","Peace","Léon Jouhaux");
INSERT INTO nobel VALUES ("1951","Physics","John Cockcroft");
INSERT INTO nobel VALUES ("1951","Physics","Ernest T.S. Walton");
INSERT INTO nobel VALUES ("1950","Chemistry","Kurt Alder");
INSERT INTO nobel VALUES ("1950","Chemistry","Otto Diels");
INSERT INTO nobel VALUES ("1950","Literature","Bertrand Russell");
INSERT INTO nobel VALUES ("1950","Medicine","Philip S. Hench");
INSERT INTO nobel VALUES ("1950","Medicine","Edward C. Kendall");
INSERT INTO nobel VALUES ("1950","Medicine","Tadeus Reichstein");
INSERT INTO nobel VALUES ("1950","Peace","Ralph Bunche");
INSERT INTO nobel VALUES ("1950","Physics","Cecil Powell");
INSERT INTO nobel VALUES ("1949","Chemistry","William F. Giauque");
INSERT INTO nobel VALUES ("1949","Literature","William Faulkner");
INSERT INTO nobel VALUES ("1949","Medicine","Walter Hess");
INSERT INTO nobel VALUES ("1949","Medicine","Egas Moniz");
INSERT INTO nobel VALUES ("1949","Peace","Lord Boyd Orr");
INSERT INTO nobel VALUES ("1949","Physics","Hideki Yukawa");
INSERT INTO nobel VALUES ("1948","Chemistry","Arne Tiselius");
INSERT INTO nobel VALUES ("1948","Literature","T.S. Eliot");
INSERT INTO nobel VALUES ("1948","Medicine","Paul Müller");
INSERT INTO nobel VALUES ("1948","Physics","Patrick M.S. Blackett");
INSERT INTO nobel VALUES ("1947","Chemistry","Sir Robert Robinson");
INSERT INTO nobel VALUES ("1947","Literature","André Gide");
INSERT INTO nobel VALUES ("1947","Medicine","Carl Cori");
INSERT INTO nobel VALUES ("1947","Medicine","Gerty Cori");
INSERT INTO nobel VALUES ("1947","Medicine","Bernardo Houssay");
INSERT INTO nobel VALUES ("1947","Peace","Friends Service Council");
INSERT INTO nobel VALUES ("1947","Peace","American Friends Service Committee");
INSERT INTO nobel VALUES ("1947","Physics","Edward V. Appleton");
INSERT INTO nobel VALUES ("1946","Chemistry","John H. Northrop");
INSERT INTO nobel VALUES ("1946","Chemistry","Wendell M. Stanley");
INSERT INTO nobel VALUES ("1946","Chemistry","James B. Sumner");
INSERT INTO nobel VALUES ("1946","Literature","Hermann Hesse");
INSERT INTO nobel VALUES ("1946","Medicine","Hermann J. Muller");
INSERT INTO nobel VALUES ("1946","Peace","Emily Greene Balch");
INSERT INTO nobel VALUES ("1946","Peace","John R. Mott");
INSERT INTO nobel VALUES ("1946","Physics","Percy W. Bridgman");
INSERT INTO nobel VALUES ("1945","Chemistry","Artturi Virtanen");
INSERT INTO nobel VALUES ("1945","Literature","Gabriela Mistral");
INSERT INTO nobel VALUES ("1945","Medicine","Ernst B. Chain");
INSERT INTO nobel VALUES ("1945","Medicine","Sir Alexander Fleming");
INSERT INTO nobel VALUES ("1945","Medicine","Sir Howard Florey");
INSERT INTO nobel VALUES ("1945","Peace","Cordell Hull");
INSERT INTO nobel VALUES ("1945","Physics","Wolfgang Pauli");
INSERT INTO nobel VALUES ("1944","Chemistry","Otto Hahn");
INSERT INTO nobel VALUES ("1944","Literature","Johannes V. Jensen");
INSERT INTO nobel VALUES ("1944","Medicine","Joseph Erlanger");
INSERT INTO nobel VALUES ("1944","Medicine","Herbert S. Gasser");
INSERT INTO nobel VALUES ("1944","Peace","International Committee of the Red Cross");
INSERT INTO nobel VALUES ("1944","Physics","Isidor Isaac Rabi");
INSERT INTO nobel VALUES ("1943","Chemistry","George de Hevesy");
INSERT INTO nobel VALUES ("1943","Medicine","Henrik Dam");
INSERT INTO nobel VALUES ("1943","Medicine","Edward A. Doisy");
INSERT INTO nobel VALUES ("1943","Physics","Otto Stern");
INSERT INTO nobel VALUES ("1939","Chemistry","Adolf Butenandt");
INSERT INTO nobel VALUES ("1939","Chemistry","Leopold Ruzicka");
INSERT INTO nobel VALUES ("1939","Literature","Frans Eemil Sillanpää");
INSERT INTO nobel VALUES ("1939","Medicine","Gerhard Domagk");
INSERT INTO nobel VALUES ("1939","Physics","Ernest Lawrence");
INSERT INTO nobel VALUES ("1938","Chemistry","Richard Kuhn");
INSERT INTO nobel VALUES ("1938","Literature","Pearl Buck");
INSERT INTO nobel VALUES ("1938","Medicine","Corneille Heymans");
INSERT INTO nobel VALUES ("1938","Peace","Nansen International Office for Refugees");
INSERT INTO nobel VALUES ("1938","Physics","Enrico Fermi");
INSERT INTO nobel VALUES ("1937","Chemistry","Norman Haworth");
INSERT INTO nobel VALUES ("1937","Chemistry","Paul Karrer");
INSERT INTO nobel VALUES ("1937","Literature","Roger Martin du Gard");
INSERT INTO nobel VALUES ("1937","Medicine","Albert Szent-Györgyi");
INSERT INTO nobel VALUES ("1937","Peace","Robert Cecil");
INSERT INTO nobel VALUES ("1937","Physics","Clinton Davisson");
INSERT INTO nobel VALUES ("1937","Physics","George Paget Thomson");
INSERT INTO nobel VALUES ("1936","Chemistry","Peter Debye");
INSERT INTO nobel VALUES ("1936","Literature","Eugene O'Neill");
INSERT INTO nobel VALUES ("1936","Medicine","Sir Henry Dale");
INSERT INTO nobel VALUES ("1936","Medicine","Otto Loewi");
INSERT INTO nobel VALUES ("1936","Peace","Carlos Saavedra Lamas");
INSERT INTO nobel VALUES ("1936","Physics","Carl D. Anderson");
INSERT INTO nobel VALUES ("1936","Physics","Victor F. Hess");
INSERT INTO nobel VALUES ("1935","Chemistry","Frédéric Joliot");
INSERT INTO nobel VALUES ("1935","Chemistry","Irène Joliot-Curie");
INSERT INTO nobel VALUES ("1935","Medicine","Hans Spemann");
INSERT INTO nobel VALUES ("1935","Peace","Carl von Ossietzky");
INSERT INTO nobel VALUES ("1935","Physics","James Chadwick");
INSERT INTO nobel VALUES ("1934","Chemistry","Harold C. Urey");
INSERT INTO nobel VALUES ("1934","Literature","Luigi Pirandello");
INSERT INTO nobel VALUES ("1934","Medicine","George R. Minot");
INSERT INTO nobel VALUES ("1934","Medicine","William P. Murphy");
INSERT INTO nobel VALUES ("1934","Medicine","George H. Whipple");
INSERT INTO nobel VALUES ("1934","Peace","Arthur Henderson");
INSERT INTO nobel VALUES ("1933","Literature","Ivan Bunin");
INSERT INTO nobel VALUES ("1933","Medicine","Thomas H. Morgan");
INSERT INTO nobel VALUES ("1933","Peace","Sir Norman Angell");
INSERT INTO nobel VALUES ("1933","Physics","Paul A.M. Dirac");
INSERT INTO nobel VALUES ("1933","Physics","Erwin Schrödinger");
INSERT INTO nobel VALUES ("1932","Chemistry","Irving Langmuir");
INSERT INTO nobel VALUES ("1932","Literature","John Galsworthy");
INSERT INTO nobel VALUES ("1932","Medicine","Edgar Adrian");
INSERT INTO nobel VALUES ("1932","Medicine","Sir Charles Sherrington");
INSERT INTO nobel VALUES ("1932","Physics","Werner Heisenberg");
INSERT INTO nobel VALUES ("1931","Chemistry","Friedrich Bergius");
INSERT INTO nobel VALUES ("1931","Chemistry","Carl Bosch");
INSERT INTO nobel VALUES ("1931","Literature","Erik Axel Karlfeldt");
INSERT INTO nobel VALUES ("1931","Medicine","Otto Warburg");
INSERT INTO nobel VALUES ("1931","Peace","Jane Addams");
INSERT INTO nobel VALUES ("1931","Peace","Nicholas Murray Butler");
INSERT INTO nobel VALUES ("1930","Chemistry","Hans Fischer");
INSERT INTO nobel VALUES ("1930","Literature","Sinclair Lewis");
INSERT INTO nobel VALUES ("1930","Medicine","Karl Landsteiner");
INSERT INTO nobel VALUES ("1930","Peace","Nathan Söderblom");
INSERT INTO nobel VALUES ("1930","Physics","Sir Venkata Raman");
INSERT INTO nobel VALUES ("1929","Chemistry","Arthur Harden");
INSERT INTO nobel VALUES ("1929","Chemistry","Hans von Euler-Chelpin");
INSERT INTO nobel VALUES ("1929","Literature","Thomas Mann");
INSERT INTO nobel VALUES ("1929","Medicine","Christiaan Eijkman");
INSERT INTO nobel VALUES ("1929","Medicine","Sir Frederick Hopkins");
INSERT INTO nobel VALUES ("1929","Peace","Frank B. Kellogg");
INSERT INTO nobel VALUES ("1929","Physics","Louis de Broglie");
INSERT INTO nobel VALUES ("1928","Chemistry","Adolf Windaus");
INSERT INTO nobel VALUES ("1928","Literature","Sigrid Undset");
INSERT INTO nobel VALUES ("1928","Medicine","Charles Nicolle");
INSERT INTO nobel VALUES ("1928","Physics","Owen Willans Richardson");
INSERT INTO nobel VALUES ("1927","Chemistry","Heinrich Wieland");
INSERT INTO nobel VALUES ("1927","Literature","Henri Bergson");
INSERT INTO nobel VALUES ("1927","Medicine","Julius Wagner-Jauregg");
INSERT INTO nobel VALUES ("1927","Peace","Ferdinand Buisson");
INSERT INTO nobel VALUES ("1927","Peace","Ludwig Quidde");
INSERT INTO nobel VALUES ("1927","Physics","Arthur H. Compton");
INSERT INTO nobel VALUES ("1927","Physics","C.T.R. Wilson");
INSERT INTO nobel VALUES ("1926","Chemistry","The Svedberg");
INSERT INTO nobel VALUES ("1926","Literature","Grazia Deledda");
INSERT INTO nobel VALUES ("1926","Medicine","Johannes Fibiger");
INSERT INTO nobel VALUES ("1926","Peace","Aristide Briand");
INSERT INTO nobel VALUES ("1926","Peace","Gustav Stresemann");
INSERT INTO nobel VALUES ("1926","Physics","Jean Baptiste Perrin");
INSERT INTO nobel VALUES ("1925","Chemistry","Richard Zsigmondy");
INSERT INTO nobel VALUES ("1925","Literature","George Bernard Shaw");
INSERT INTO nobel VALUES ("1925","Peace","Sir Austen Chamberlain");
INSERT INTO nobel VALUES ("1925","Peace","Charles G. Dawes");
INSERT INTO nobel VALUES ("1925","Physics","James Franck");
INSERT INTO nobel VALUES ("1925","Physics","Gustav Hertz");
INSERT INTO nobel VALUES ("1924","Literature","Wladyslaw Reymont");
INSERT INTO nobel VALUES ("1924","Medicine","Willem Einthoven");
INSERT INTO nobel VALUES ("1924","Physics","Manne Siegbahn");
INSERT INTO nobel VALUES ("1923","Chemistry","Fritz Pregl");
INSERT INTO nobel VALUES ("1923","Literature","William Butler Yeats");
INSERT INTO nobel VALUES ("1923","Medicine","Frederick G. Banting");
INSERT INTO nobel VALUES ("1923","Medicine","John Macleod");
INSERT INTO nobel VALUES ("1923","Physics","Robert A. Millikan");
INSERT INTO nobel VALUES ("1922","Chemistry","Francis W. Aston");
INSERT INTO nobel VALUES ("1922","Literature","Jacinto Benavente");
INSERT INTO nobel VALUES ("1922","Medicine","Archibald V. Hill");
INSERT INTO nobel VALUES ("1922","Medicine","Otto Meyerhof");
INSERT INTO nobel VALUES ("1922","Peace","Fridtjof Nansen");
INSERT INTO nobel VALUES ("1922","Physics","Niels Bohr");
INSERT INTO nobel VALUES ("1921","Chemistry","Frederick Soddy");
INSERT INTO nobel VALUES ("1921","Literature","Anatole France");
INSERT INTO nobel VALUES ("1921","Peace","Hjalmar Branting");
INSERT INTO nobel VALUES ("1921","Peace","Christian Lange");
INSERT INTO nobel VALUES ("1921","Physics","Albert Einstein");
INSERT INTO nobel VALUES ("1920","Chemistry","Walther Nernst");
INSERT INTO nobel VALUES ("1920","Literature","Knut Hamsun");
INSERT INTO nobel VALUES ("1920","Medicine","August Krogh");
INSERT INTO nobel VALUES ("1920","Peace","Léon Bourgeois");
INSERT INTO nobel VALUES ("1920","Physics","Charles Edouard Guillaume");
INSERT INTO nobel VALUES ("1919","Literature","Carl Spitteler");
INSERT INTO nobel VALUES ("1919","Medicine","Jules Bordet");
INSERT INTO nobel VALUES ("1919","Peace","Woodrow Wilson");
INSERT INTO nobel VALUES ("1919","Physics","Johannes Stark");
INSERT INTO nobel VALUES ("1918","Chemistry","Fritz Haber");
INSERT INTO nobel VALUES ("1918","Physics","Max Planck");
INSERT INTO nobel VALUES ("1917","Literature","Karl Gjellerup");
INSERT INTO nobel VALUES ("1917","Literature","Henrik Pontoppidan");
INSERT INTO nobel VALUES ("1917","Peace","International Committee of the Red Cross");
INSERT INTO nobel VALUES ("1917","Physics","Charles Glover Barkla");
INSERT INTO nobel VALUES ("1916","Literature","Verner von Heidenstam");
INSERT INTO nobel VALUES ("1915","Chemistry","Richard Willstätter");
INSERT INTO nobel VALUES ("1915","Literature","Romain Rolland");
INSERT INTO nobel VALUES ("1915","Physics","William Bragg");
INSERT INTO nobel VALUES ("1915","Physics","Lawrence Bragg");
INSERT INTO nobel VALUES ("1914","Chemistry","Theodore W. Richards");
INSERT INTO nobel VALUES ("1914","Medicine","Robert Bárány");
INSERT INTO nobel VALUES ("1914","Physics","Max von Laue");
INSERT INTO nobel VALUES ("1913","Chemistry","Alfred Werner");
INSERT INTO nobel VALUES ("1913","Literature","Rabindranath Tagore");
INSERT INTO nobel VALUES ("1913","Medicine","Charles Richet");
INSERT INTO nobel VALUES ("1913","Peace","Henri La Fontaine");
INSERT INTO nobel VALUES ("1913","Physics","Heike Kamerlingh Onnes");
INSERT INTO nobel VALUES ("1912","Chemistry","Victor Grignard");
INSERT INTO nobel VALUES ("1912","Chemistry","Paul Sabatier");
INSERT INTO nobel VALUES ("1912","Literature","Gerhart Hauptmann");
INSERT INTO nobel VALUES ("1912","Medicine","Alexis Carrel");
INSERT INTO nobel VALUES ("1912","Peace","Elihu Root");
INSERT INTO nobel VALUES ("1912","Physics","Gustaf Dalén");
INSERT INTO nobel VALUES ("1911","Chemistry","Marie Curie");
INSERT INTO nobel VALUES ("1911","Literature","Maurice Maeterlinck");
INSERT INTO nobel VALUES ("1911","Medicine","Allvar Gullstrand");
INSERT INTO nobel VALUES ("1911","Peace","Tobias Asser");
INSERT INTO nobel VALUES ("1911","Peace","Alfred Fried");
INSERT INTO nobel VALUES ("1911","Physics","Wilhelm Wien");
INSERT INTO nobel VALUES ("1910","Chemistry","Otto Wallach");
INSERT INTO nobel VALUES ("1910","Literature","Paul Heyse");
INSERT INTO nobel VALUES ("1910","Medicine","Albrecht Kossel");
INSERT INTO nobel VALUES ("1910","Peace","Permanent International Peace Bureau");
INSERT INTO nobel VALUES ("1910","Physics","Johannes Diderik van der Waals");
INSERT INTO nobel VALUES ("1909","Chemistry","Wilhelm Ostwald");
INSERT INTO nobel VALUES ("1909","Literature","Selma Lagerlöf");
INSERT INTO nobel VALUES ("1909","Medicine","Theodor Kocher");
INSERT INTO nobel VALUES ("1909","Peace","Auguste Beernaert");
INSERT INTO nobel VALUES ("1909","Peace","Paul Henri d'Estournelles de Constant");
INSERT INTO nobel VALUES ("1909","Physics","Ferdinand Braun");
INSERT INTO nobel VALUES ("1909","Physics","Guglielmo Marconi");
INSERT INTO nobel VALUES ("1908","Chemistry","Ernest Rutherford");
INSERT INTO nobel VALUES ("1908","Literature","Rudolf Eucken");
INSERT INTO nobel VALUES ("1908","Medicine","Paul Ehrlich");
INSERT INTO nobel VALUES ("1908","Medicine","Ilya Mechnikov");
INSERT INTO nobel VALUES ("1908","Peace","Klas Pontus Arnoldson");
INSERT INTO nobel VALUES ("1908","Peace","Fredrik Bajer");
INSERT INTO nobel VALUES ("1908","Physics","Gabriel Lippmann");
INSERT INTO nobel VALUES ("1907","Chemistry","Eduard Buchner");
INSERT INTO nobel VALUES ("1907","Literature","Rudyard Kipling");
INSERT INTO nobel VALUES ("1907","Medicine","Alphonse Laveran");
INSERT INTO nobel VALUES ("1907","Peace","Ernesto Teodoro Moneta");
INSERT INTO nobel VALUES ("1907","Peace","Louis Renault");
INSERT INTO nobel VALUES ("1907","Physics","Albert A. Michelson");
INSERT INTO nobel VALUES ("1906","Chemistry","Henri Moissan");
INSERT INTO nobel VALUES ("1906","Literature","Giosuè Carducci");
INSERT INTO nobel VALUES ("1906","Medicine","Camillo Golgi");
INSERT INTO nobel VALUES ("1906","Medicine","Santiago Ramón y Cajal");
INSERT INTO nobel VALUES ("1906","Peace","Theodore Roosevelt");
INSERT INTO nobel VALUES ("1906","Physics","J.J. Thomson");
INSERT INTO nobel VALUES ("1905","Chemistry","Adolf von Baeyer");
INSERT INTO nobel VALUES ("1905","Literature","Henryk Sienkiewicz");
INSERT INTO nobel VALUES ("1905","Medicine","Robert Koch");
INSERT INTO nobel VALUES ("1905","Peace","Bertha von Suttner");
INSERT INTO nobel VALUES ("1905","Physics","Philipp Lenard");
INSERT INTO nobel VALUES ("1904","Chemistry","Sir William Ramsay");
INSERT INTO nobel VALUES ("1904","Literature","José Echegaray");
INSERT INTO nobel VALUES ("1904","Literature","Frédéric Mistral");
INSERT INTO nobel VALUES ("1904","Medicine","Ivan Pavlov");
INSERT INTO nobel VALUES ("1904","Peace","Institute of International Law");
INSERT INTO nobel VALUES ("1904","Physics","Lord Rayleigh");
INSERT INTO nobel VALUES ("1903","Chemistry","Svante Arrhenius");
INSERT INTO nobel VALUES ("1903","Literature","Bjørnstjerne Bjørnson");
INSERT INTO nobel VALUES ("1903","Medicine","Niels Ryberg Finsen");
INSERT INTO nobel VALUES ("1903","Peace","Randal Cremer");
INSERT INTO nobel VALUES ("1903","Physics","Henri Becquerel");
INSERT INTO nobel VALUES ("1903","Physics","Pierre Curie");
INSERT INTO nobel VALUES ("1903","Physics","Marie Curie");
INSERT INTO nobel VALUES ("1902","Chemistry","Emil Fischer");
INSERT INTO nobel VALUES ("1902","Literature","Theodor Mommsen");
INSERT INTO nobel VALUES ("1902","Medicine","Ronald Ross");
INSERT INTO nobel VALUES ("1902","Peace","Élie Ducommun");
INSERT INTO nobel VALUES ("1902","Peace","Albert Gobat");
INSERT INTO nobel VALUES ("1902","Physics","Hendrik A. Lorentz");
INSERT INTO nobel VALUES ("1902","Physics","Pieter Zeeman");
INSERT INTO nobel VALUES ("1901","Chemistry","Jacobus H. van 't Hoff");
INSERT INTO nobel VALUES ("1901","Literature","Sully Prudhomme");
INSERT INTO nobel VALUES ("1901","Medicine","Emil von Behring");
INSERT INTO nobel VALUES ("1901","Peace","Henry Dunant");
INSERT INTO nobel VALUES ("1901","Peace","Frédéric Passy");
INSERT INTO nobel VALUES ("1901","Physics","Wilhelm Conrad Röntgen");
